blueprint:
  domain: automation
  name: Sonoff TRVZB External Temperature Sensor
  description: This blueprint synchronises the local temperature of one or more Sonoff TRVZBs with an external temperature sensor.

  input:
    external_temperature_sensor:
      name: External Temperature Sensor
      description: The entity of the external temperature sensor device that represents the temperature value.
      selector:
        entity:
          filter:
            - domain: sensor
              device_class: temperature

    trv_external_temperature_input:
      name: Sonoff TRVZB(s)
      description: The entity of the Sonoff TRVZB device that represents the external temperature value.
      selector:
        entity:
          multiple: true
          filter:
            - domain: number
              device_class: temperature

triggers:
  - trigger: state
    entity_id: !input external_temperature_sensor
variables:
  external_temperature_sensor: !input external_temperature_sensor
actions:
  - action: number.set_value
    metadata: {}
    data:
      value: "{{ states(external_temperature_sensor) | float }}"
      entity_id: !input trv_external_temperature_input
mode: single